from core.chat.prompts import (
    ROOT_SYSTEM_PROMPT,
    MAIN_SYSTEM_PROMPT,
    VIDEO_AGENT_SYSTEM_PROMPT,
    MANIM_SYSTEM_PROMPT,
    VOICE_MUSIC_SYSTEM_PROMPT,
)

__all__ = [
    "ROOT_SYSTEM_PROMPT",
    "MAIN_SYSTEM_PROMPT",
    "VIDEO_AGENT_SYSTEM_PROMPT",
    "MANIM_SYSTEM_PROMPT",
    "VOICE_MUSIC_SYSTEM_PROMPT",
]
